# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "jquery.counterup", to: "jquery.counterup.min.js"
pin "bootsnav", to: "bootsnav.js"
pin "bootstrap.min", to: "bootstrap.min.js"
pin "custom", to: "custom.js"
pin "feather.min", to: "feather.min.js"
pin "jquery", to: "jquery.js"
pin "slick.min", to: "slick.min.js"
pin "waypoints.min", to: "waypoints.min.js"
